-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 20:30:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmacia` DEFAULT CHARACTER SET utf8 ;
USE `farmacia` ;

-- -----------------------------------------------------
-- Table `farmacia`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`usuario` (
  `idusuario` INT NOT NULL auto_increment,
  `cedula` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `password` INT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`laboratorio` (
  `idlaboratorio` INT NOT NULL auto_increment,
  `nombre` VARCHAR(45) NULL,
  `descrip` VARCHAR(45) NULL,
  PRIMARY KEY (`idlaboratorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`medicamento` (
  `idmedicamento` INT NOT NULL auto_increment,
  `nombre` VARCHAR(45) NULL,
  `descrip` VARCHAR(45) NULL,
  `fecha_venc` DATE NULL,
  `cant` VARCHAR(45) NULL,
  `fecha_creado` DATE NULL,
  `precio` INT NULL,
  `usuario_idusuario` INT NOT NULL,
  `laboratorio_idlaboratorio` INT NOT NULL,
  PRIMARY KEY (`idmedicamento`),
  -- INDEX `fk_medicamento_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  -- INDEX `fk_medicamento_laboratorio1_idx` (`laboratorio_idlaboratorio` ASC) VISIBLE,
  -- CONSTRAINT `fk_medicamento_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `farmacia`.`usuario` (`idusuario`),
    -- ON DELETE NO ACTION
    -- ON UPDATE NO ACTION,
  -- CONSTRAINT `fk_medicamento_laboratorio1`
    FOREIGN KEY (`laboratorio_idlaboratorio`)
    REFERENCES `farmacia`.`laboratorio` (`idlaboratorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`cliente` (
  `idcliente` INT NOT NULL auto_increment,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `fecha_naci` DATE NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`venta` (
  `idventa` INT NOT NULL auto_increment,
  `fecha_venta` DATETIME NULL,
  `valor_total` INT NULL,
  `cliente_idcliente` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idventa`),
  -- INDEX `fk_venta_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  -- INDEX `fk_venta_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  -- CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `farmacia`.`cliente` (`idcliente`),
    -- ON DELETE NO ACTION
    -- ON UPDATE NO ACTION,
  -- CONSTRAINT `fk_venta_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `farmacia`.`usuario` (`idusuario`))
    -- ON DELETE NO ACTION
    -- ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`detalle_venta` (
  `iddetalle_venta` INT NOT NULL auto_increment,
  `cant` INT NULL,
  `medicamento_idmedicamento` INT NOT NULL,
  `venta_idventa` INT NOT NULL,
  PRIMARY KEY (`iddetalle_venta`),
  -- INDEX `fk_detalle_venta_medicamento1_idx` (`medicamento_idmedicamento` ASC) VISIBLE,
  -- INDEX `fk_detalle_venta_venta1_idx` (`venta_idventa` ASC) VISIBLE,
  -- CONSTRAINT `fk_detalle_venta_medicamento1`
    FOREIGN KEY (`medicamento_idmedicamento`)
    REFERENCES `farmacia`.`medicamento` (`idmedicamento`),
    -- ON DELETE NO ACTION
    -- ON UPDATE NO ACTION,
  -- CONSTRAINT `fk_detalle_venta_venta1`
    FOREIGN KEY (`venta_idventa`)
    REFERENCES `farmacia`.`venta` (`idventa`))
    -- ON DELETE NO ACTION
    -- ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNmedicamento_ibfk_2IQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `farmacia`.`usuario` (`cedula`, `nombre`, `apellido`, `correo`, `usuario`, `password`) VALUES ('1094', 'sebas', 'pala', 'sebas@pala.com', 'admin', '123');

INSERT INTO `farmacia`.`laboratorio` (`nombre`, `descrip`) VALUES ('genfar', 'jajajajajajaja');

INSERT INTO `farmacia`.`medicamento` (`nombre`, `descrip`, `fecha_venc`, `cant`, `fecha_creado`, `precio`, `usuario_idusuario`, `laboratorio_idlaboratorio`) VALUES ('acetaminofem', 'no se', '2032-02-02', '1', '2020-02-02', '1', '1', '1');

